services:
  - type: web
    name: django-admin-auth
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn admin_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
databases:
  - name: django-db
    databaseName: admin_db
    user: admin_user
